"use client";

/**
 * InspectorShell — panel selector + panel router for the presentation inspector.
 *
 * Reads the available panels for the current selection type via
 * `availablePanels` from `inspector-panel-ui.ts` and renders the selected panel.
 *
 * When the selection changes, the shell preserves compatible panels and
 * replaces incompatible panels with the default panel for the new context.
 */

import { useId, useState, type JSX, type ReactNode } from "react";
import { X } from "lucide-react";

import type {
  SlideChildNode,
  SlideNode,
  SemanticTemplateKind,
  NodeSourceMetadata,
  SlideControls,
  SlideProps,
  DeckChromeConfig,
} from "@/lib/presentation/schema";
import type { ResolvedRenderNode } from "@/lib/presentation/render-tree";
import type {
  BlendMode,
  EffectStyle,
  ShadowStyle,
  StyleBinding,
  StyleObject,
  StylePatch,
} from "@/lib/presentation/style-schema";
import type {
  PresentationDiagnostic,
  DiagnosticAction,
} from "@/lib/presentation/diagnostics";
import type { SourceBlockIndexEntry } from "@/lib/presentation/block-index";
import type { SourceLinkClassification } from "@/lib/presentation/source-links";

import {
  availablePanels,
  defaultPanelForNode,
  resolveInspectorPanelContinuity,
  type InspectorPanelId,
} from "@/lib/presentation/inspector-panel-ui";
import {
  currentObjectAlignCommandDescriptor,
  currentObjectReorderCommandDescriptor,
  type CurrentObjectReorderMode,
} from "@/lib/presentation/current-object-command-descriptors";

import { cx } from "@/components/ui/tokens";
import type {
  SelectionAlignMode,
  SelectionDistributeMode,
  SelectionMatchSizeMode,
} from "../toolbar/context-toolbar";

import { DiagnosticsPanel } from "./diagnostics-panel";
import { DeckChromePanel } from "./deck-chrome-panel";
import { InspectorPanelSelect } from "./inspector-panel-select";
import { LayersPanel } from "./layers-panel";
import { LocalOverrideBadge } from "./local-override-badge";
import { LocalStylePanel } from "./local-style-panel";
import { NodeContentPanel } from "./node-content-panel";
import { NodeGeometryPanel } from "./node-geometry-panel";
import { NodeSourcePanel } from "./node-source-panel";
import { SlideControlsPanel } from "./slide-controls-panel";
import { SlideSettingsPanel } from "./slide-settings-panel";
import { StyleBindingPanel } from "./style-binding-panel";
import { updateImageCropSide } from "./numeric-sanitization";

const DEFAULT_GLOW_COLOR = "#4f46e5";
const DEFAULT_SHADOW_COLOR = "#000000";
const DEFAULT_SHADOW_OPACITY = 0.18;
const DEFAULT_SHADOW: ShadowStyle = {
  xPt: 0,
  yPt: 8,
  blurPt: 18,
  color: DEFAULT_SHADOW_COLOR,
  opacity: DEFAULT_SHADOW_OPACITY,
};

// ---------------------------------------------------------------------------
// Sub-panel wrappers
// ---------------------------------------------------------------------------

function PanelSection({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) {
  return (
    <div className={cx("min-h-0 flex-1 overflow-y-auto", className)}>
      {children}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Notes mini-panel (simple textarea)
// ---------------------------------------------------------------------------

function NotesPanel({
  notes,
  onUpdateNotes,
}: {
  notes: string | undefined;
  onUpdateNotes: (notes: string) => void;
}) {
  return (
    <PanelSection>
      <div className="p-3">
        <label className="flex flex-col gap-1.5">
          <span className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
            Speaker Notes
          </span>
          <textarea
            rows={6}
            value={notes ?? ""}
            onChange={(e) => onUpdateNotes(e.currentTarget.value)}
            placeholder="Add speaker notes…"
            className="w-full resize-none rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface p-2 text-xs text-ds-text-primary placeholder:text-ds-text-muted focus:border-ds-accent focus:outline-none focus:ring-2 focus:ring-ds-focus-ring/20"
          />
        </label>
      </div>
    </PanelSection>
  );
}

// ---------------------------------------------------------------------------
// Decoration panel
// ---------------------------------------------------------------------------

function DecorationPanel({
  source,
  onDetach,
}: {
  source: "themeDecoration" | "deckChrome";
  onDetach: () => void;
}) {
  const title = source === "deckChrome" ? "Deck Chrome" : "Theme Decoration";
  return (
    <PanelSection>
      <div className="flex flex-col gap-2 p-3">
        <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
          {title}
        </h4>
        <p className="text-xs text-ds-text-secondary">
          This element is generated by the{" "}
          {source === "deckChrome" ? "deck" : "theme package"}. Detach it to
          make independent edits.
        </p>
        <button
          type="button"
          onClick={onDetach}
          className="self-start rounded-[var(--ds-radius-sm,6px)] border border-ds-border-subtle bg-ds-surface px-3 py-1 text-xs font-medium text-ds-text-primary transition-colors hover:bg-ds-surface-raised"
        >
          {source === "deckChrome"
            ? "Detach from deck chrome"
            : "Detach from theme"}
        </button>
      </div>
    </PanelSection>
  );
}

function ActionButton({
  children,
  onClick,
  disabled,
}: {
  children: ReactNode;
  onClick: () => void;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      className="rounded-[var(--ds-radius-sm,6px)] border border-ds-border-subtle px-2 py-1 text-xs font-medium text-ds-text-secondary hover:bg-ds-state-hover disabled:opacity-40"
    >
      {children}
    </button>
  );
}

function MultiArrangePanel({
  selectedCount,
  onAlignSelection,
  onDistributeSelection,
  onMatchSize,
  onReorderSelection,
  onGroupSelection,
  onUngroupSelection,
}: {
  selectedCount: number;
  onAlignSelection: (mode: SelectionAlignMode) => void;
  onDistributeSelection: (mode: SelectionDistributeMode) => void;
  onMatchSize: (mode: SelectionMatchSizeMode) => void;
  onReorderSelection: (mode: CurrentObjectReorderMode) => void;
  onGroupSelection: () => void;
  onUngroupSelection: () => void;
}) {
  return (
    <PanelSection>
      <section className="flex flex-col gap-3 px-3 py-2.5">
        <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
          Arrange {selectedCount} nodes
        </h4>
        <div className="grid grid-cols-3 gap-1.5">
          <ActionButton onClick={() => onAlignSelection("left")}>
            {currentObjectAlignCommandDescriptor("left").shortLabel}
          </ActionButton>
          <ActionButton onClick={() => onAlignSelection("center")}>
            {currentObjectAlignCommandDescriptor("center").shortLabel}
          </ActionButton>
          <ActionButton onClick={() => onAlignSelection("right")}>
            {currentObjectAlignCommandDescriptor("right").shortLabel}
          </ActionButton>
          <ActionButton onClick={() => onAlignSelection("top")}>
            {currentObjectAlignCommandDescriptor("top").shortLabel}
          </ActionButton>
          <ActionButton onClick={() => onAlignSelection("middle")}>
            {currentObjectAlignCommandDescriptor("middle").shortLabel}
          </ActionButton>
          <ActionButton onClick={() => onAlignSelection("bottom")}>
            {currentObjectAlignCommandDescriptor("bottom").shortLabel}
          </ActionButton>
        </div>
        <div className="grid grid-cols-2 gap-1.5">
          {(["forward", "backward", "front", "back"] as const).map((mode) => (
            <ActionButton key={mode} onClick={() => onReorderSelection(mode)}>
              {currentObjectReorderCommandDescriptor(mode).shortLabel}
            </ActionButton>
          ))}
        </div>
        <div className="grid grid-cols-2 gap-1.5">
          <ActionButton
            disabled={selectedCount < 3}
            onClick={() => onDistributeSelection("horizontal")}
          >
            Distribute H
          </ActionButton>
          <ActionButton
            disabled={selectedCount < 3}
            onClick={() => onDistributeSelection("vertical")}
          >
            Distribute V
          </ActionButton>
          <ActionButton onClick={() => onMatchSize("width")}>
            Match width
          </ActionButton>
          <ActionButton onClick={() => onMatchSize("height")}>
            Match height
          </ActionButton>
          <ActionButton onClick={() => onMatchSize("both")}>
            Match both
          </ActionButton>
        </div>
        <div className="grid grid-cols-2 gap-1.5">
          <ActionButton onClick={onGroupSelection}>Group</ActionButton>
          <ActionButton onClick={onUngroupSelection}>Ungroup</ActionButton>
        </div>
      </section>
    </PanelSection>
  );
}

function SingleArrangePanel({
  onAlignSelection,
  onReorderSelection,
}: {
  onAlignSelection: (mode: SelectionAlignMode) => void;
  onReorderSelection: (mode: CurrentObjectReorderMode) => void;
}) {
  return (
    <section className="flex flex-col gap-3 px-3 py-2.5">
      <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
        Arrange
      </h4>
      <div className="grid grid-cols-3 gap-1.5">
        <ActionButton onClick={() => onAlignSelection("left")}>
          {currentObjectAlignCommandDescriptor("left").shortLabel}
        </ActionButton>
        <ActionButton onClick={() => onAlignSelection("center")}>
          {currentObjectAlignCommandDescriptor("center").shortLabel}
        </ActionButton>
        <ActionButton onClick={() => onAlignSelection("right")}>
          {currentObjectAlignCommandDescriptor("right").shortLabel}
        </ActionButton>
        <ActionButton onClick={() => onAlignSelection("top")}>
          {currentObjectAlignCommandDescriptor("top").shortLabel}
        </ActionButton>
        <ActionButton onClick={() => onAlignSelection("middle")}>
          {currentObjectAlignCommandDescriptor("middle").shortLabel}
        </ActionButton>
        <ActionButton onClick={() => onAlignSelection("bottom")}>
          {currentObjectAlignCommandDescriptor("bottom").shortLabel}
        </ActionButton>
      </div>
      <div className="grid grid-cols-2 gap-1.5">
        {(["forward", "backward", "front", "back"] as const).map((mode) => (
          <ActionButton key={mode} onClick={() => onReorderSelection(mode)}>
            {currentObjectReorderCommandDescriptor(mode).inspectorSingleLabel}
          </ActionButton>
        ))}
      </div>
    </section>
  );
}

function RangeField({
  label,
  value,
  min,
  max,
  step,
  onChange,
  display,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (value: number) => void;
  display?: (value: number) => string;
}) {
  return (
    <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
      <span className="flex items-center justify-between gap-2">
        <span>{label}</span>
        <span className="font-mono text-[11px] text-ds-text-muted">
          {display ? display(value) : value}
        </span>
      </span>
      <input
        type="range"
        value={value}
        min={min}
        max={max}
        step={step}
        onChange={(event) => onChange(Number(event.currentTarget.value))}
      />
    </label>
  );
}

function NumberField({
  label,
  value,
  min,
  max,
  step = 1,
  onChange,
}: {
  label: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  onChange: (value: number) => void;
}) {
  return (
    <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
      {label}
      <input
        type="number"
        value={Number.isFinite(value) ? value : 0}
        min={min}
        max={max}
        step={step}
        onChange={(event) => onChange(Number(event.currentTarget.value))}
        className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary outline-none focus:border-ds-accent focus:ring-2 focus:ring-ds-focus-ring/20"
      />
    </label>
  );
}

function AdjustPanel({
  node,
  onUpdateContent,
  onUpdateLocalStyle,
}: {
  node: SlideChildNode;
  onUpdateContent: (patch: Record<string, unknown>) => void;
  onUpdateLocalStyle: (patch: StylePatch) => void;
}) {
  if (node.type !== "image") {
    return (
      <PanelSection>
        <div className="p-3 text-xs text-ds-text-muted">
          Image adjustment controls are available for image nodes.
        </div>
      </PanelSection>
    );
  }

  const crop = node.content.crop ?? { top: 0, right: 0, bottom: 0, left: 0 };
  const opacity = node.localStyle?.opacity ?? 1;
  const brightness = node.localStyle?.image?.brightness ?? 1;
  const contrast = node.localStyle?.image?.contrast ?? 1;
  const saturation = node.localStyle?.image?.saturation ?? 1;
  const blur =
    node.localStyle?.effect?.kind === "blur"
      ? (node.localStyle.effect.radiusPt ?? 0)
      : 0;

  return (
    <PanelSection>
      <section className="flex flex-col gap-3 px-3 py-2.5">
        <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
          Image Adjust
        </h4>
        <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
          Fit mode
          <select
            value={node.content.fit ?? "cover"}
            onChange={(event) =>
              onUpdateContent({ fit: event.currentTarget.value })
            }
            className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
          >
            {(["contain", "cover", "fill", "none"] as const).map((fit) => (
              <option key={fit} value={fit}>
                {fit}
              </option>
            ))}
          </select>
        </label>
        <RangeField
          label="Opacity"
          value={opacity}
          min={0}
          max={1}
          step={0.05}
          display={(value) => `${Math.round(value * 100)}%`}
          onChange={(value) => onUpdateLocalStyle({ opacity: value })}
        />
        <RangeField
          label="Brightness"
          value={brightness}
          min={0}
          max={2}
          step={0.05}
          display={(value) => `${Math.round(value * 100)}%`}
          onChange={(value) =>
            onUpdateLocalStyle({ image: { brightness: value } })
          }
        />
        <RangeField
          label="Contrast"
          value={contrast}
          min={0}
          max={2}
          step={0.05}
          display={(value) => `${Math.round(value * 100)}%`}
          onChange={(value) =>
            onUpdateLocalStyle({ image: { contrast: value } })
          }
        />
        <RangeField
          label="Saturation"
          value={saturation}
          min={0}
          max={2}
          step={0.05}
          display={(value) => `${Math.round(value * 100)}%`}
          onChange={(value) =>
            onUpdateLocalStyle({ image: { saturation: value } })
          }
        />
        <RangeField
          label="Blur"
          value={blur}
          min={0}
          max={32}
          step={1}
          display={(value) => `${value} pt`}
          onChange={(value) =>
            onUpdateLocalStyle({
              effect:
                value === 0
                  ? { kind: "none" }
                  : { kind: "blur", radiusPt: value },
            })
          }
        />
        <div className="grid grid-cols-2 gap-2">
          {(["top", "right", "bottom", "left"] as const).map((side) => (
            <NumberField
              key={side}
              label={`Crop ${side}`}
              value={crop[side]}
              min={0}
              max={95}
              onChange={(value) => {
                const nextCrop = updateImageCropSide(crop, side, value);
                if (nextCrop !== undefined) {
                  onUpdateContent({ crop: nextCrop });
                }
              }}
            />
          ))}
        </div>
        <button
          type="button"
          onClick={() =>
            onUpdateContent({
              crop: { top: 0, right: 0, bottom: 0, left: 0 },
            })
          }
          className="self-start rounded-[var(--ds-radius-sm,6px)] border border-ds-border-subtle px-2 py-1 text-xs font-medium text-ds-text-secondary hover:bg-ds-state-hover"
        >
          Reset crop
        </button>
        <button
          type="button"
          onClick={() =>
            onUpdateLocalStyle({
              opacity: 1,
              image: { brightness: 1, contrast: 1, saturation: 1 },
              effect: { kind: "none" },
            })
          }
          className="self-start rounded-[var(--ds-radius-sm,6px)] border border-ds-border-subtle px-2 py-1 text-xs font-medium text-ds-text-secondary hover:bg-ds-state-hover"
        >
          Reset adjustments
        </button>
      </section>
    </PanelSection>
  );
}

type LocalStyleUpdater = (patch: StylePatch) => void;
type LocalEffectStyle = NonNullable<StylePatch["effect"]>;
type LocalShadowStyle = StylePatch["shadow"];

function resolveEffectForKind(kind: string): EffectStyle {
  if (kind === "blur") {
    return { kind: "blur", radiusPt: 12 };
  }

  if (kind === "glow") {
    return {
      kind: "glow",
      color: DEFAULT_GLOW_COLOR,
      blurPt: 14,
      opacity: 0.35,
    };
  }

  if (kind === "glass") {
    return { kind: "glass", intensity: "medium" };
  }

  return { kind: "none" };
}

function shadowPatch(
  shadow: LocalShadowStyle,
  patch: Partial<ShadowStyle>,
): ShadowStyle {
  return {
    xPt: patch.xPt ?? shadow?.xPt ?? DEFAULT_SHADOW.xPt,
    yPt: patch.yPt ?? shadow?.yPt ?? DEFAULT_SHADOW.yPt,
    blurPt: patch.blurPt ?? shadow?.blurPt ?? DEFAULT_SHADOW.blurPt,
    color:
      patch.color ??
      (typeof shadow?.color === "string" ? shadow.color : DEFAULT_SHADOW.color),
    opacity: patch.opacity ?? shadow?.opacity ?? DEFAULT_SHADOW_OPACITY,
  };
}

function renderEffectControls({
  effect,
  onUpdateLocalStyle,
}: {
  effect: LocalEffectStyle;
  onUpdateLocalStyle: LocalStyleUpdater;
}) {
  return (
    <>
      <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
        Effect
        <select
          value={effect.kind}
          onChange={(event) =>
            onUpdateLocalStyle({
              effect: resolveEffectForKind(event.currentTarget.value),
            })
          }
          className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
        >
          <option value="none">None</option>
          <option value="blur">Blur</option>
          <option value="glow">Glow</option>
          <option value="glass">Glass</option>
        </select>
      </label>
      {effect.kind === "blur" ? (
        <RangeField
          label="Blur radius"
          value={effect.radiusPt ?? 12}
          min={0}
          max={48}
          step={1}
          display={(value) => `${value} pt`}
          onChange={(value) =>
            onUpdateLocalStyle({ effect: { kind: "blur", radiusPt: value } })
          }
        />
      ) : null}
      {effect.kind === "glow" ? (
        <div className="grid grid-cols-2 gap-2">
          <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
            Glow color
            <input
              type="color"
              value={
                typeof effect.color === "string"
                  ? effect.color
                  : DEFAULT_GLOW_COLOR
              }
              onChange={(event) =>
                onUpdateLocalStyle({
                  effect: { ...effect, color: event.currentTarget.value },
                })
              }
              className="h-8 rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface"
            />
          </label>
          <NumberField
            label="Glow blur"
            value={effect.blurPt ?? 14}
            min={0}
            max={64}
            onChange={(value) =>
              onUpdateLocalStyle({ effect: { ...effect, blurPt: value } })
            }
          />
          <div className="col-span-2">
            <RangeField
              label="Glow opacity"
              value={effect.opacity ?? 0.35}
              min={0}
              max={1}
              step={0.05}
              display={(value) => `${Math.round(value * 100)}%`}
              onChange={(value) =>
                onUpdateLocalStyle({ effect: { ...effect, opacity: value } })
              }
            />
          </div>
        </div>
      ) : null}
    </>
  );
}

function renderBlendModeSelect({
  blendMode,
  onUpdateLocalStyle,
}: {
  blendMode: BlendMode;
  onUpdateLocalStyle: LocalStyleUpdater;
}) {
  return (
    <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
      Blend mode
      <select
        value={blendMode}
        onChange={(event) =>
          onUpdateLocalStyle({
            blendMode: event.currentTarget.value as BlendMode,
          })
        }
        className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
      >
        <option value="normal">Normal</option>
        <option value="multiply">Multiply</option>
        <option value="screen">Screen</option>
        <option value="overlay">Overlay</option>
        <option value="darken">Darken</option>
        <option value="lighten">Lighten</option>
      </select>
    </label>
  );
}

function renderShadowControls({
  shadow,
  onUpdateLocalStyle,
}: {
  shadow: LocalShadowStyle;
  onUpdateLocalStyle: LocalStyleUpdater;
}) {
  const shadowEnabled = shadow === undefined || shadow.opacity !== 0;
  const updateShadow = (patch: Partial<ShadowStyle>) =>
    onUpdateLocalStyle({ shadow: shadowPatch(shadow, patch) });

  return (
    <>
      <label className="flex items-center gap-2 text-xs text-ds-text-secondary">
        <input
          type="checkbox"
          checked={shadowEnabled}
          onChange={(event) =>
            onUpdateLocalStyle({
              shadow: event.currentTarget.checked
                ? shadowPatch(shadow, {})
                : {
                    xPt: 0,
                    yPt: 0,
                    blurPt: 0,
                    color: DEFAULT_SHADOW_COLOR,
                    opacity: 0,
                  },
            })
          }
        />
        Shadow
      </label>
      {shadowEnabled ? (
        <div className="grid grid-cols-2 gap-2">
          <NumberField
            label="X offset"
            value={shadow?.xPt ?? DEFAULT_SHADOW.xPt}
            onChange={(value) => updateShadow({ xPt: value })}
          />
          <NumberField
            label="Y offset"
            value={shadow?.yPt ?? DEFAULT_SHADOW.yPt}
            onChange={(value) => updateShadow({ yPt: value })}
          />
          <NumberField
            label="Blur"
            value={shadow?.blurPt ?? DEFAULT_SHADOW.blurPt}
            min={0}
            onChange={(value) => updateShadow({ blurPt: value })}
          />
          <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
            Color
            <input
              type="color"
              value={
                typeof shadow?.color === "string"
                  ? shadow.color
                  : DEFAULT_SHADOW_COLOR
              }
              onChange={(event) =>
                updateShadow({ color: event.currentTarget.value })
              }
              className="h-8 rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface"
            />
          </label>
          <div className="col-span-2">
            <RangeField
              label="Shadow opacity"
              value={shadow?.opacity ?? DEFAULT_SHADOW_OPACITY}
              min={0}
              max={1}
              step={0.05}
              display={(value) => `${Math.round(value * 100)}%`}
              onChange={(value) => updateShadow({ opacity: value })}
            />
          </div>
        </div>
      ) : null}
    </>
  );
}

function EffectsPanel({
  node,
  onUpdateLocalStyle,
  onResetToTheme,
}: {
  node: SlideChildNode | undefined;
  onUpdateLocalStyle: LocalStyleUpdater;
  onResetToTheme: () => void;
}) {
  const opacity = node?.localStyle?.opacity ?? 1;
  const shadow = node?.localStyle?.shadow;
  const effect = node?.localStyle?.effect ?? { kind: "none" as const };
  const blendMode = node?.localStyle?.blendMode ?? "normal";

  return (
    <PanelSection>
      <section className="flex flex-col gap-3 px-3 py-2.5">
        <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
          Effects
        </h4>
        <RangeField
          label="Opacity"
          value={opacity}
          min={0}
          max={1}
          step={0.05}
          display={(value) => `${Math.round(value * 100)}%`}
          onChange={(value) => onUpdateLocalStyle({ opacity: value })}
        />
        {renderEffectControls({ effect, onUpdateLocalStyle })}
        {renderBlendModeSelect({ blendMode, onUpdateLocalStyle })}
        {renderShadowControls({ shadow, onUpdateLocalStyle })}
        <button
          type="button"
          onClick={onResetToTheme}
          className="self-start rounded-[var(--ds-radius-sm,6px)] border border-ds-border-subtle px-2 py-1 text-xs font-medium text-ds-text-secondary hover:bg-ds-state-hover"
        >
          Reset to theme
        </button>
      </section>
    </PanelSection>
  );
}

// ---------------------------------------------------------------------------
// Arrangement panel (stub — wraps NodeGeometryPanel)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface InspectorShellProps {
  // Slide context
  activeSlide: SlideNode | undefined;
  deckChrome: DeckChromeConfig | undefined;
  selectedNode: SlideChildNode | undefined;
  selectedResolvedStyle?: StyleObject;
  selectedIds: string[];
  isDecorationSelected: boolean;
  selectedGeneratedSource?: "themeDecoration" | "deckChrome";
  diagnostics: PresentationDiagnostic[];
  layerDecorations?: readonly ResolvedRenderNode[];
  layerChrome?: readonly ResolvedRenderNode[];

  // Slide-level handlers
  onUpdateControls: (patch: Partial<SlideControls>) => void;
  onUpdateProps: (patch: Partial<SlideProps>) => void;
  onUpdateDeckChrome: (patch: Partial<DeckChromeConfig>) => void;
  onUpdateSlideAttributes: (patch: { name?: string; notes?: string }) => void;
  onUpdateSlideLocalStyle: (patch: StylePatch) => void;
  onResetSlideLocalStyle: () => void;
  onUpdateSlideSource: (source: NodeSourceMetadata | undefined) => void;
  onUploadSlideBackgroundImage?: () => void;

  // Node-level handlers
  onUpdateSelectedLayout: (patch: Record<string, unknown>) => void;
  onUpdateSelectedAttributes: (patch: {
    locked?: boolean;
    hidden?: boolean;
  }) => void;
  onUpdateSelectedContent: (patch: Record<string, unknown>) => void;
  onUpdateSelectedLocalStyle: (patch: StylePatch) => void;
  assetResolver?: (assetId: string) => string | undefined;
  onReplaceImage?: () => void;
  onReplaceVisual?: () => void;
  onResetToTheme: () => void;
  onUpdateSelectedSource: (source: NodeSourceMetadata | undefined) => void;
  onRefreshSelectedSource?: () => void;
  sourceRefreshPending?: boolean;
  onUnlinkSelectedSource?: () => void;
  onRelinkSelectedSource?: (block: SourceBlockIndexEntry) => void;
  selectedSourceClassification?: SourceLinkClassification;
  sourceBlocks?: readonly SourceBlockIndexEntry[];
  onChangeStyleBinding: (binding: StyleBinding) => void;
  onAlignSelection: (mode: SelectionAlignMode) => void;
  onDistributeSelection: (mode: SelectionDistributeMode) => void;
  onMatchSize: (mode: SelectionMatchSizeMode) => void;
  onReorderSelection?: (mode: CurrentObjectReorderMode) => void;
  onGroupSelection: () => void;
  onUngroupSelection: () => void;

  // Layers
  onSelectLayer: (nodeId: string) => void;
  onUpdateLayer: (
    nodeId: string,
    patch: { name?: string; locked?: boolean; hidden?: boolean },
  ) => void;
  onReorderLayer: (nodeId: string, targetIndex: number) => void;

  // Decoration
  onDetachDecoration: () => void;

  // Diagnostics
  onDiagnosticAction: (
    action: DiagnosticAction,
    diagnostic: PresentationDiagnostic,
  ) => void;

  // Template
  TEMPLATE_OPTIONS: { kind: SemanticTemplateKind; label: string }[];
  activeTemplate: { layouts: { id: string }[] } | undefined;
  activeLayoutId: string | undefined;
  onReapplyTemplate: (kind: SemanticTemplateKind, layoutId?: string) => void;

  // Mode
  selectionMode: "normal" | "layers";
  onToggleSelectionMode: () => void;
  initialPanel?: InspectorPanelId;
  onClose?: () => void;
}

export function InspectorShell({
  activeSlide,
  deckChrome,
  selectedNode,
  selectedResolvedStyle,
  selectedIds,
  isDecorationSelected,
  selectedGeneratedSource,
  diagnostics,
  layerDecorations,
  layerChrome,
  onUpdateControls,
  onUpdateProps,
  onUpdateDeckChrome,
  onUpdateSlideAttributes,
  onUpdateSlideLocalStyle,
  onResetSlideLocalStyle,
  onUpdateSlideSource,
  onUploadSlideBackgroundImage,
  onUpdateSelectedLayout,
  onUpdateSelectedAttributes,
  onUpdateSelectedContent,
  onUpdateSelectedLocalStyle,
  assetResolver,
  onReplaceImage,
  onReplaceVisual,
  onResetToTheme,
  onUpdateSelectedSource,
  onRefreshSelectedSource,
  sourceRefreshPending = false,
  onUnlinkSelectedSource,
  onRelinkSelectedSource,
  selectedSourceClassification,
  sourceBlocks,
  onChangeStyleBinding,
  onAlignSelection,
  onDistributeSelection,
  onMatchSize,
  onReorderSelection = () => undefined,
  onGroupSelection,
  onUngroupSelection,
  onSelectLayer,
  onUpdateLayer,
  onReorderLayer,
  onDetachDecoration,
  onDiagnosticAction,
  TEMPLATE_OPTIONS,
  activeTemplate,
  activeLayoutId,
  onReapplyTemplate,
  selectionMode,
  onToggleSelectionMode,
  initialPanel,
  onClose,
}: InspectorShellProps): JSX.Element {
  const nodeForRouting = isDecorationSelected ? null : (selectedNode ?? null);
  const multiSelect = selectedIds.length > 1;
  const panels = availablePanels(nodeForRouting, {
    multiSelect,
    isDecoration: isDecorationSelected,
    hasDiagnostics: diagnostics.length > 0,
  });
  const defaultPanel = defaultPanelForNode(
    nodeForRouting,
    isDecorationSelected,
  );

  const [activePanel, setActivePanel] = useState<InspectorPanelId>(() =>
    resolveInspectorPanelContinuity({
      activePanel: initialPanel,
      panels,
      defaultPanel,
    }),
  );

  const effectivePanel = resolveInspectorPanelContinuity({
    activePanel,
    panels,
    defaultPanel,
  });

  const inspectorPanelSelectId = useId();
  const inspectorPanelId = (panelId: string) =>
    `presentation-inspector-panel-${panelId}`;

  function handlePanelSelect(panel: InspectorPanelId) {
    setActivePanel(panel);
    const nextLayersMode = panel === "layers";
    if (nextLayersMode !== (selectionMode === "layers")) {
      onToggleSelectionMode();
    }
  }

  // Identity label next to the panel selector
  let identityLabel = "Inspector";
  if (isDecorationSelected) {
    identityLabel =
      selectedGeneratedSource === "deckChrome" ? "Deck chrome" : "Decoration";
  } else if (selectedNode) {
    identityLabel =
      selectedNode.type.charAt(0).toUpperCase() + selectedNode.type.slice(1);
    if (selectedNode.name) identityLabel = selectedNode.name;
  } else if (activeSlide) {
    identityLabel = activeSlide.name ?? "Slide";
  }

  return (
    <aside
      role="region"
      aria-label="Inspector"
      className="relative z-panel flex h-full w-80 shrink-0 flex-col overflow-hidden bg-ds-surface"
    >
      {/* Identity header */}
      <div className="flex items-center justify-between gap-2 border-b border-ds-border-subtle px-3 py-2">
        <span className="truncate text-xs font-medium text-ds-text-primary">
          {identityLabel}
        </span>
        <div className="flex shrink-0 items-center gap-1.5">
          <InspectorPanelSelect
            id={inspectorPanelSelectId}
            panels={panels}
            value={effectivePanel}
            diagnosticsCount={diagnostics.length}
            onChange={handlePanelSelect}
          />
          {onClose ? (
            <button
              type="button"
              aria-label="Close inspector"
              onClick={onClose}
              className="flex h-7 w-7 items-center justify-center rounded-ds-sm text-ds-text-muted transition-colors hover:bg-ds-state-hover hover:text-ds-text-primary"
            >
              <X size={14} aria-hidden="true" />
            </button>
          ) : null}
        </div>
      </div>

      {/* Panel content */}
      <div
        id={inspectorPanelId(effectivePanel)}
        role="tabpanel"
        aria-labelledby={inspectorPanelSelectId}
        className="min-h-0 flex-1 overflow-y-auto"
      >
        {/* Slide panel */}
        {effectivePanel === "slide" && activeSlide && (
          <PanelSection>
            <section className="flex flex-col gap-1.5 px-3 py-2.5">
              <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
                Template
              </h4>
              <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
                Kind
                <select
                  value={activeSlide.template.kind}
                  onChange={(e) =>
                    onReapplyTemplate(
                      e.currentTarget.value as SemanticTemplateKind,
                    )
                  }
                  className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
                >
                  {TEMPLATE_OPTIONS.map((t) => (
                    <option key={t.kind} value={t.kind}>
                      {t.label}
                    </option>
                  ))}
                </select>
              </label>
              {activeTemplate && (
                <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
                  Layout
                  <select
                    value={activeLayoutId ?? activeTemplate.layouts[0]?.id}
                    onChange={(e) =>
                      onReapplyTemplate(
                        activeSlide.template.kind,
                        e.currentTarget.value,
                      )
                    }
                    className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
                  >
                    {activeTemplate.layouts.map((l) => (
                      <option key={l.id} value={l.id}>
                        {l.id}
                      </option>
                    ))}
                  </select>
                </label>
              )}
            </section>
            <SlideControlsPanel
              controls={activeSlide.controls}
              props={activeSlide.props}
              onUpdateControls={onUpdateControls}
              onUpdateProps={onUpdateProps}
            />
            <DeckChromePanel
              chrome={deckChrome}
              slideProps={activeSlide.props}
              onUpdateChrome={onUpdateDeckChrome}
              onUpdateSlideProps={onUpdateProps}
            />
            <SlideSettingsPanel
              slide={activeSlide}
              onUpdateSlide={onUpdateSlideAttributes}
              onUpdateSource={onUpdateSlideSource}
              onUpdateLocalStyle={onUpdateSlideLocalStyle}
              onResetLocalStyle={onResetSlideLocalStyle}
              assetResolver={assetResolver}
              onUploadBackgroundImage={onUploadSlideBackgroundImage}
            />
          </PanelSection>
        )}

        {/* Notes panel */}
        {effectivePanel === "notes" && (
          <NotesPanel
            notes={activeSlide?.notes}
            onUpdateNotes={(notes) => onUpdateSlideAttributes({ notes })}
          />
        )}

        {/* Text panel — content + style controls */}
        {(effectivePanel === "text" || effectivePanel === "shape") &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <div className="px-3 py-2">
                <LocalOverrideBadge
                  localStyle={selectedNode.localStyle}
                  onResetToTheme={onResetToTheme}
                />
              </div>
              <NodeContentPanel
                node={selectedNode}
                onUpdateContent={onUpdateSelectedContent}
              />
              <LocalStylePanel
                node={selectedNode}
                resolvedStyle={selectedResolvedStyle}
                onUpdateLocalStyle={onUpdateSelectedLocalStyle}
              />
            </PanelSection>
          )}

        {/* Image / visual / line / table content panel */}
        {(effectivePanel === "image" ||
          effectivePanel === "visual" ||
          effectivePanel === "line" ||
          effectivePanel === "table") &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <div className="px-3 py-2">
                <LocalOverrideBadge
                  localStyle={selectedNode.localStyle}
                  onResetToTheme={onResetToTheme}
                />
              </div>
              <NodeContentPanel
                node={selectedNode}
                onUpdateContent={onUpdateSelectedContent}
                assetResolver={assetResolver}
                onReplaceImage={
                  selectedNode.type === "image" ? onReplaceImage : undefined
                }
                onReplaceVisual={
                  selectedNode.type === "visual" ? onReplaceVisual : undefined
                }
              />
              <LocalStylePanel
                node={selectedNode}
                resolvedStyle={selectedResolvedStyle}
                onUpdateLocalStyle={onUpdateSelectedLocalStyle}
              />
            </PanelSection>
          )}

        {/* Adjust panel */}
        {effectivePanel === "adjust" && selectedNode && (
          <AdjustPanel
            node={selectedNode}
            onUpdateContent={onUpdateSelectedContent}
            onUpdateLocalStyle={onUpdateSelectedLocalStyle}
          />
        )}

        {/* Arrange panel */}
        {effectivePanel === "arrange" && multiSelect && (
          <MultiArrangePanel
            selectedCount={selectedIds.length}
            onAlignSelection={onAlignSelection}
            onDistributeSelection={onDistributeSelection}
            onMatchSize={onMatchSize}
            onReorderSelection={onReorderSelection}
            onGroupSelection={onGroupSelection}
            onUngroupSelection={onUngroupSelection}
          />
        )}

        {effectivePanel === "arrange" &&
          !multiSelect &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <div className="px-3 py-2">
                <LocalOverrideBadge
                  localStyle={selectedNode.localStyle}
                  onResetToTheme={onResetToTheme}
                />
              </div>
              <SingleArrangePanel
                onAlignSelection={onAlignSelection}
                onReorderSelection={onReorderSelection}
              />
              <NodeGeometryPanel
                node={selectedNode}
                onUpdateLayout={
                  onUpdateSelectedLayout as Parameters<
                    typeof NodeGeometryPanel
                  >[0]["onUpdateLayout"]
                }
                onUpdateAttributes={onUpdateSelectedAttributes}
              />
            </PanelSection>
          )}

        {/* Effects panel */}
        {effectivePanel === "effects" && (
          <EffectsPanel
            node={selectedNode}
            onUpdateLocalStyle={onUpdateSelectedLocalStyle}
            onResetToTheme={onResetToTheme}
          />
        )}

        {/* Source panel */}
        {effectivePanel === "source" &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <NodeSourcePanel
                node={selectedNode}
                onUpdateSource={onUpdateSelectedSource}
                onRefreshSource={onRefreshSelectedSource}
                sourceRefreshPending={sourceRefreshPending}
                onUnlinkSource={onUnlinkSelectedSource}
                onRelinkSource={onRelinkSelectedSource}
                classification={selectedSourceClassification}
                availableBlocks={sourceBlocks}
              />
            </PanelSection>
          )}

        {/* Style panel */}
        {effectivePanel === "style" &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <StyleBindingPanel
                role={selectedNode.role}
                binding={selectedNode.style}
                onChangeStyleBinding={onChangeStyleBinding}
              />
              <LocalStylePanel
                node={selectedNode}
                resolvedStyle={selectedResolvedStyle}
                onUpdateLocalStyle={onUpdateSelectedLocalStyle}
              />
            </PanelSection>
          )}

        {/* Layers panel */}
        {effectivePanel === "layers" && activeSlide && (
          <PanelSection>
            <LayersPanel
              nodes={activeSlide.children}
              decorations={layerDecorations}
              chrome={layerChrome}
              selectedIds={selectedIds}
              onSelectNode={onSelectLayer}
              onUpdateNode={onUpdateLayer}
              onReorderNode={onReorderLayer}
            />
          </PanelSection>
        )}

        {/* Decoration panel */}
        {effectivePanel === "decoration" && isDecorationSelected && (
          <DecorationPanel
            source={selectedGeneratedSource ?? "themeDecoration"}
            onDetach={onDetachDecoration}
          />
        )}

        {/* Diagnostics panel */}
        {effectivePanel === "diagnostics" && (
          <PanelSection>
            <DiagnosticsPanel
              diagnostics={diagnostics}
              onAction={onDiagnosticAction}
              hideInfo={false}
            />
          </PanelSection>
        )}
      </div>
    </aside>
  );
}
