import { test } from "node:test";
import assert from "node:assert/strict";

import * as presentation from "@/lib/presentation";

test("presentation barrel exposes the stable runtime surface", () => {
  const expectedRuntimeExports = [
    "isValidId",
    "makeDiagnostic",
    "DiagnosticCollector",
    "resolveToken",
    "STYLE_REFS",
    "isStyleRef",
    "DECK_SCHEMA_VERSION",
    "safeParseDeck",
    "BUILT_IN_THEME_PACKAGE_IDS",
    "DEFAULT_BUILT_IN_THEME_PACKAGE_ID",
    "BUILT_IN_THEME_PACKAGE_ALIASES",
    "isBuiltInThemePackageId",
    "resolveBuiltInThemePackageId",
    "validateThemePackage",
    "resolveNodeStyle",
    "resolveTheme",
    "SEMANTIC_TEMPLATE_KINDS",
    "isSemanticTemplateKind",
    "SemanticTemplateRegistry",
    "selectLayout",
    "isSlotValue",
    "repairSemanticDeckPlan",
    "compileSlide",
    "resetIdCounter",
    "slideSpecFromSlide",
    "emptySlideSpecFromLayout",
    "resolveDeckRenderTree",
    "buildExportSpec",
    "insertSlide",
    "insertBlankSlide",
    "duplicateSlide",
    "deleteSlide",
    "moveSlide",
    "applyTemplate",
    "updateSlideControls",
    "updateSlideAttributes",
    "updateSlideLocalStyle",
    "resetSlideLocalStyle",
    "updateSlideSourceMetadata",
    "setThemePackage",
    "insertNode",
    "pasteNodes",
    "updateNodeContent",
    "resetImageCrop",
    "updateNodeLayout",
    "updateNodeRotation",
    "updateNodeLayouts",
    "updateNodeAttributes",
    "updateNodeSourceMetadata",
    "moveNodesBy",
    "deleteNodes",
    "duplicateNodes",
    "updateNodeStyleBinding",
    "updateLocalStyle",
    "resetLocalStyleOverride",
    "detachDecoration",
    "groupNodes",
    "ungroupNodes",
    "reorderZIndex",
    "updateAssetMetadata",
    "CURRENT_OBJECT_COMMAND_SURFACES",
    "CURRENT_OBJECT_COMMAND_SURFACE_LABELS",
    "CURRENT_OBJECT_DISABLED_REASONS",
    "CURRENT_OBJECT_DISABLED_REASON_LABELS",
    "CURRENT_OBJECT_COMMAND_FAMILIES",
    "CURRENT_OBJECT_INSERT_NODE_COMMAND_DESCRIPTORS",
    "CURRENT_OBJECT_ALIGN_COMMAND_DESCRIPTORS",
    "CURRENT_OBJECT_REORDER_COMMAND_DESCRIPTORS",
    "CURRENT_OBJECT_COMMAND_DESCRIPTORS",
    "findCurrentObjectCommandDescriptor",
    "currentObjectCommandDescriptor",
    "currentObjectCommandDescriptorsForSurface",
    "currentObjectAlignCommandDescriptor",
    "currentObjectReorderCommandDescriptor",
    "currentObjectInsertNodeCommandDescriptor",
    "resolveSlideCommandPaletteCommands",
    "filterSlideCommandPaletteCommands",
    "alignmentGuidesForFrames",
    "normalizeStageGuideInputs",
    "normalizeStageGuidePosition",
    "snapFrameToStageGuides",
    "stageGuideInputKey",
    "normalizeSelectionFrame",
    "selectNodesInFrame",
    "createDefaultTemplateRegistry",
    "BUILT_IN_TEMPLATES",
    "NEUTRAL_THEME_PACKAGE",
    "THEME_PACKAGE_REGISTRY",
    "resolveThemePackageId",
    "getThemePackage",
    "listThemePackages",
    "resolveThemePackageForDeck",
    "createBlankDeck",
    "openDeckFromJson",
    "looksLikeDeck",
    "buildPptxSpec",
    "textContentToPptxRuns",
    "presentationShapeToName",
    "applyPptxTextOp",
    "applyPptxShapeOp",
    "applyPptxImageOp",
    "applyPptxConnectorOp",
    "applyPptxTableOp",
    "applyPptxSpec",
    "exportDeckAsPPTX",
    "SUPPORTED_VISUAL_COLOR_CHANNELS",
    "DEFAULT_VISUAL_CHANNEL_COLORS",
    "isSupportedVisualColorChannel",
    "normalizeVisualChannelColors",
    "visualChannelColorWithDefaults",
  ] as const;

  for (const name of expectedRuntimeExports) {
    assert.ok(name in presentation, `${name} should be exported by the barrel`);
  }
  assert.equal(presentation.DECK_SCHEMA_VERSION, 7);
  assert.equal(presentation.isSupportedVisualColorChannel("primary"), true);
  assert.deepEqual(
    presentation.visualChannelColorWithDefaults({ primary: "#111111" }).primary,
    "#111111",
  );
});
