import { writeFileSync } from "node:fs";
import { buildSlideFontFaceCss } from "../src/lib/presentation/slide-fonts";

const header = `/*\n * AUTOGENERATED from src/lib/presentation/slide-fonts.ts (buildSlideFontFaceCss()).\n * Do not edit by hand. Run: npm run slide-fonts:generate\n */\n`;
writeFileSync("src/app/slide-fonts.css", header + buildSlideFontFaceCss());
process.stdout.write("Wrote src/app/slide-fonts.css\n");
